swagger: '2.0'
info:
  title: Electricity Loss Prediction API
  version: "1.0"
  description: API for predicting the chance of losing electricity based on location and hurricane category.
host: electricity-service-dot-my-api-prediction-project.ue.r.appspot.com
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /predict:
    post:
      summary: Make a prediction about electricity loss.
      description: Predicts the chance of losing electricity given the latitude, longitude, and hurricane category.
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              latitude:
                type: number
                example: 29.7604
              longitude:
                type: number
                example: -95.3698
              hurricane_category:
                type: integer
                example: 3
      responses:
        '200':
          description: Prediction data
          schema:
            type: object
            properties:
              predicted_chance_of_losing_electricity:
                type: string
                example: '98.34%'
              reason:
                type: string
                example: 'The nearest power source (solar power plant) is 0.43 miles away.'
        '400':
          description: Bad Request. Invalid input received.
        '500':
          description: Internal Server Error.
